#!/bin/bash

# s3simple is a small, simple bash s3 client with minimal dependencies.
# See http://github.com/paulhammond/s3simple for documentation.
s3simple() {
  url="$1"
  file="${2:--}"

  if [ "${url:0:5}" != "s3://" ]; then
    echo "Need an s3 url"
    exit 1
  fi

  if [ -z $AWS_ACCESS_KEY_ID ]; then
    echo "Need AWS_ACCESS_KEY_ID to be set"
    exit 1
  fi

  if [ -z $AWS_SECRET_ACCESS_KEY ]; then
    echo "Need AWS_SECRET_ACCESS_KEY to be set"
    exit 1
  fi

  path=${url:4}

  verb=GET
  date="$(date -u '+%a, %e %b %Y %H:%M:%S +0000')"

  # GET \n (md5 blank) \n (type blank) \n date \n path
  printf -v string_to_sign "GET\n\n\n%s\n/%s" "$date" "$path"
  signature=$(echo -n "$string_to_sign" | openssl sha1 -binary -hmac "${AWS_SECRET_ACCESS_KEY}" | openssl base64)
  authorization="AWS ${AWS_ACCESS_KEY_ID}:${signature}"

  curl -o ${file} -s -v -f -H Date:"${date}" -H Authorization:"${authorization}" http://s3.amazonaws.com/${path}
}

s3simple "$@"
