#!/bin/bash

# todo: check AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set

bucket="$1"
path="$2"
file="${3:--}"
verb=GET

date="$(date -u '+%a, %e %b %Y %H:%M:%S +0000')"

#headers=
#date:date

#GET
#(md5 blank)
#(type blank)
#date
#bucket/path
printf -v string_to_sign "GET\n\n\n%s\n/%s%s" "$date" "$bucket" "$path"

signature=$(echo -n "$string_to_sign" | openssl sha1 -binary -hmac "${AWS_SECRET_ACCESS_KEY}" | openssl base64)
authorization="AWS ${AWS_ACCESS_KEY_ID}:${signature}"

curl -o ${file} -s -v -f -H Date:"${date}" -H Authorization:"${authorization}" http://s3.amazonaws.com/${bucket}${path}
